name: circuit_superintendent_tool
description: A new Flutter project.

publish_to: "none"

version: 1.0.2

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flagsmith: ^5.0.1
  flutter_bloc: ^8.1.5
  lottie: ^2.7.0
  package_info: ^2.0.2
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0
  app_version_compare: ^1.0.0
  get_it: ^7.6.7
  url_launcher: ^6.2.4
  google_fonts: ^5.1.0
  fgen: ^1.0.0
  melos: ^3.4.0
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.2
  path: any
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lotties/
    - .env
